version: '3.9'

networks:
  pubnet:
    driver: bridge

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "pubnet"
      POSTGRES_PASSWORD: "pubnet"
    networks:
      - pubnet

  seq:
    image: datalust/seq
    restart: always
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "5380:80"

  caddy:
    image: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
    networks:
      - pubnet

  api:
    build:
      dockerfile: PubNet.API/Dockerfile
      target: final
    depends_on:
      - database
      - caddy
    volumes:
      - "./appsettings.json:/app/appsettings.Production.json"
    networks:
      - pubnet

  worker:
    build:
      dockerfile: PubNet.Worker/Dockerfile
      target: final
    depends_on:
      - database
    volumes:
      - "./appsettings.json:/app/appsettings.Production.json"
    networks:
      - pubnet

  frontend:
    build:
      dockerfile: PubNet.Frontend/Dockerfile
      target: final
    depends_on:
      - api
    volumes:
      - "./appsettings-frontend.json:/app/wwwroot/appsettings.Production.json"
