name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
    #   schedule:
    #     - cron: '38 20 * * *'
    push:
        branches: [ "main" ]
        # Publish semver tags as releases.
        tags: [ 'v*.*.*' ]
    pull_request:
        branches: [ "main" ]

env:
    # Use docker.io for Docker Hub if empty
    REGISTRY: ghcr.io
    # github.repository as <account>/<repo>
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Setup Docker buildx
                uses: docker/setup-buildx-action@v2

            -   name: Log into registry ${{ env.REGISTRY }}
                if: github.event_name != 'pull_request'
                uses: docker/login-action@v2
                with:
                    registry: ${{ env.REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Extract Docker metadata (PubNet.API)
                id: meta-api
                uses: docker/metadata-action@v4
                with:
                    images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/api

            -   name: Build and push Docker image (PubNet.API)
                id: build-and-push-api
                uses: docker/build-push-action@v4
                with:
                    context: .
                    file: PubNet.API/Dockerfile
                    push: ${{ github.event_name != 'pull_request' }}
                    tags: ${{ steps.meta-api.outputs.tags }}
                    labels: ${{ steps.meta-api.outputs.labels }}
                    cache-from: type=gha
                    cache-to: type=gha,mode=max

            -   name: Extract Docker metadata (PubNet.Worker)
                id: meta-worker
                uses: docker/metadata-action@v4
                with:
                    images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/worker

            -   name: Build and push Docker image (PubNet.Worker)
                id: build-and-push-worker
                uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
                with:
                    context: .
                    file: PubNet.Worker/Dockerfile
                    push: ${{ github.event_name != 'pull_request' }}
                    tags: ${{ steps.meta-worker.outputs.tags }}
                    labels: ${{ steps.meta-worker.outputs.labels }}
                    cache-from: type=gha
                    cache-to: type=gha,mode=max

            -   name: Extract Docker metadata (PubNet.Frontend)
                id: meta-worker
                uses: docker/metadata-action@v4
                with:
                    images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend

            -   name: Build and push Docker image (PubNet.Frontend)
                id: build-and-push-frontend
                uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
                with:
                    context: .
                    file: PubNet.Frontend/Dockerfile
                    push: ${{ github.event_name != 'pull_request' }}
                    tags: ${{ steps.meta-frontend.outputs.tags }}
                    labels: ${{ steps.meta-frontend.outputs.labels }}
                    cache-from: type=gha
                    cache-to: type=gha,mode=max
